### ISSUE TITLE
Bug fixed in upstream k-rail chart

### ISSUE THREAD

**Issue by js-timbirkett** [geek-cookbook/charts-archived#1]
Hi 👋  @funkypenguin 

Could the upstream k-rail be merged into the charts please? There was a bug that has been fixed and merged in: https://github.com/cruise-automation/k-rail/pull/71

Thanks 🐧

**Comment by funkypenguin** [comment]
Hey @js-timbirkett!

Done 🍔 s! Commit which updated the chart repo is https://github.com/geek-cookbook/helm-k-rail/commit/774d2a6c75b69ad42da70e58174b304be66fbf12

Cheers!
D
